services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      LANG: "pt_BR.UTF-8"
      LC_ALL: "pt_BR.UTF-8"
      LC_COLLATE: "pt_BR.UTF-8"
      LC_CTYPE: "pt_BR.UTF-8"
    volumes:
      - ./local-database:/var/lib/postgresql/data
